  
name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore PillowFight.App/
    - name: Build
      run: dotnet build PillowFight.App/ --no-restore
    - name: Test
      run: dotnet test PillowFight.App/ --no-build --verbosity normal
    - name: publish
      run: dotnet publish PillowFight.App/ --configuration Release -o ./publish
    - name: deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: Pillow-Fight-Game # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: ./publish
